# Generated by Django 4.0.3 on 2022-04-07 01:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('garage', models.IntegerField(blank=True, default=0, null=True)),
                ('sqft', models.IntegerField(blank=True, null=True)),
                ('main_photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('is_published', models.BooleanField(default=True)),
                ('list_data', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
