# Generated by Django 4.0.3 on 2022-04-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0003_alter_listing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'permissions': (('can_edit', 'Update Listing'), ('can_delete', 'Delete Listing'), ('can_create', 'Create Listing'))},
        ),
    ]
