# Generated by Django 4.0.3 on 2022-04-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0004_alter_listing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'permissions': (('can_edit', 'Update Listing'), ('can_delete', 'Delete Listing'), ('can_create', 'Create Listing'), ('can_Lease', 'Can Lease'))},
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='is_published',
            new_name='List',
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
