# Generated by Django 4.0.3 on 2022-04-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0005_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='lease',
            field=models.FileField(null=True, upload_to='Docs/lease/{self.id}'),
        ),
        migrations.AddField(
            model_name='listing',
            name='otherdocument1',
            field=models.FileField(null=True, upload_to='Docs/other/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='otherdocument2',
            field=models.FileField(null=True, upload_to='Docs/other/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='otherdocument3',
            field=models.FileField(null=True, upload_to='Docs/other/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='tenantFirstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='tenantLastName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='tenantPicture',
            field=models.ImageField(blank=True, upload_to='photos/tenants/%Y/%m/%d'),
        ),
    ]
