# Generated by Django 4.0.3 on 2022-04-12 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyManagement', '0006_listing_lease_listing_otherdocument1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('Listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='propertyManagement.listing')),
                ('tenantFirstName', models.CharField(max_length=50)),
                ('tenantLastName', models.CharField(max_length=50)),
                ('tenantPicture', models.ImageField(blank=True, upload_to='photos/tenants/%Y/%m/%d')),
                ('lease', models.FileField(null=True, upload_to='Docs/lease/')),
                ('otherdocument1', models.FileField(blank=True, null=True, upload_to='Docs/other/')),
                ('otherdocument2', models.FileField(blank=True, null=True, upload_to='Docs/other/')),
                ('otherdocument3', models.FileField(blank=True, null=True, upload_to='Docs/other/')),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='lease',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='otherdocument1',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='otherdocument2',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='otherdocument3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='tenantFirstName',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='tenantLastName',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='tenantPicture',
        ),
    ]
