# Generated by Django 4.0.3 on 2022-04-01 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='photo_main',
            new_name='main_photo',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_1',
            new_name='photo1',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_2',
            new_name='photo2',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_3',
            new_name='photo3',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_4',
            new_name='photo4',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_5',
            new_name='photo5',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_6',
            new_name='photo6',
        ),
    ]
