# Generated by Django 4.0.3 on 2022-04-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rename_photo_main_listing_main_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='lot_size',
        ),
    ]
