# Generated by Django 4.0.3 on 2022-04-01 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_remove_listing_lot_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='sqft',
        ),
    ]
