# Generated by Django 4.0.3 on 2022-04-01 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_remove_listing_sqft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='main_photo',
        ),
    ]
