# Generated by Django 4.0.3 on 2022-04-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_remove_listing_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sqft',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='media/photos/%Y/%m/%d'),
        ),
    ]
