# Generated by Django 4.0.3 on 2022-04-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_listing_sqft_alter_listing_photo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
